INSERT INTO MOVIE_in_genre_GENRE (movie_movieId, tmdbId, genre_name) VALUES ('NULL', 'NULL');
INSERT INTO MOVIE_in_genre_GENRE (movie_movieId, tmdbId, genre_name) VALUES ('NULL', 'NULL');
INSERT INTO MOVIE_in_genre_GENRE (movie_movieId, tmdbId, genre_name) VALUES ('NULL', 'NULL');
INSERT INTO MOVIE_in_genre_GENRE (movie_movieId, tmdbId, genre_name) VALUES ('NULL', 'NULL');
INSERT INTO MOVIE_in_genre_GENRE (movie_movieId, tmdbId, genre_name) VALUES ('NULL', 'NULL');
INSERT INTO MOVIE_in_genre_GENRE (movie_movieId, tmdbId, genre_name) VALUES ('NULL', 'NULL');
INSERT INTO MOVIE_in_genre_GENRE (movie_movieId, tmdbId, genre_name) VALUES ('NULL', 'NULL');
INSERT INTO MOVIE_in_genre_GENRE (movie_movieId, tmdbId, genre_name) VALUES ('NULL', 'NULL');
INSERT INTO MOVIE_in_genre_GENRE (movie_movieId, tmdbId, genre_name) VALUES ('NULL', 'NULL');
INSERT INTO MOVIE_in_genre_GENRE (movie_movieId, tmdbId, genre_name) VALUES ('NULL', 'NULL');
INSERT INTO MOVIE_in_genre_GENRE (movie_movieId, tmdbId, genre_name) VALUES ('NULL', 'NULL');
INSERT INTO MOVIE_in_genre_GENRE (movie_movieId, tmdbId, genre_name) VALUES ('NULL', 'NULL');
INSERT INTO USER_TABLE_rated_MOVIE (user_table_userId, movie_movieId, tmdbId, timestamp, rating) VALUES ('NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO USER_TABLE_rated_MOVIE (user_table_userId, movie_movieId, tmdbId, timestamp, rating) VALUES ('NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO USER_TABLE_rated_MOVIE (user_table_userId, movie_movieId, tmdbId, timestamp, rating) VALUES ('NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO USER_TABLE_rated_MOVIE (user_table_userId, movie_movieId, tmdbId, timestamp, rating) VALUES ('NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO USER_TABLE_rated_MOVIE (user_table_userId, movie_movieId, tmdbId, timestamp, rating) VALUES ('NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO USER_TABLE_rated_MOVIE (user_table_userId, movie_movieId, tmdbId, timestamp, rating) VALUES ('NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO USER_TABLE_rated_MOVIE (user_table_userId, movie_movieId, tmdbId, timestamp, rating) VALUES ('NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO USER_TABLE_rated_MOVIE (user_table_userId, movie_movieId, tmdbId, timestamp, rating) VALUES ('NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO USER_TABLE_rated_MOVIE (user_table_userId, movie_movieId, tmdbId, timestamp, rating) VALUES ('NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO USER_TABLE_rated_MOVIE (user_table_userId, movie_movieId, tmdbId, timestamp, rating) VALUES ('NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO USER_TABLE_rated_MOVIE (user_table_userId, movie_movieId, tmdbId, timestamp, rating) VALUES ('NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO USER_TABLE_rated_MOVIE (user_table_userId, movie_movieId, tmdbId, timestamp, rating) VALUES ('NULL', 'NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_acted_in_MOVIE (person_actor_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_acted_in_MOVIE (person_actor_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_acted_in_MOVIE (person_actor_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_acted_in_MOVIE (person_actor_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_acted_in_MOVIE (person_actor_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_acted_in_MOVIE (person_actor_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_acted_in_MOVIE (person_actor_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_acted_in_MOVIE (person_actor_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_acted_in_MOVIE (person_actor_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_acted_in_MOVIE (person_actor_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_acted_in_MOVIE (person_actor_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_acted_in_MOVIE (person_actor_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_acted_in_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_acted_in_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_acted_in_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_acted_in_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_acted_in_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_acted_in_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_acted_in_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_acted_in_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_acted_in_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_acted_in_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_acted_in_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_acted_in_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_directed_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_directed_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_directed_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_directed_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_directed_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_directed_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_directed_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_directed_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_directed_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_directed_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_directed_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_ACTOR_DIRECTOR_directed_MOVIE (person_actor_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_DIRECTOR_directed_MOVIE (person_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_DIRECTOR_directed_MOVIE (person_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_DIRECTOR_directed_MOVIE (person_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_DIRECTOR_directed_MOVIE (person_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_DIRECTOR_directed_MOVIE (person_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_DIRECTOR_directed_MOVIE (person_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_DIRECTOR_directed_MOVIE (person_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_DIRECTOR_directed_MOVIE (person_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_DIRECTOR_directed_MOVIE (person_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_DIRECTOR_directed_MOVIE (person_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_DIRECTOR_directed_MOVIE (person_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
INSERT INTO PERSON_DIRECTOR_directed_MOVIE (person_director_id, movie_movieId, tmdbId, role) VALUES ('NULL', 'NULL', 'NULL');
